### ISSUE TITLE
Is this repo updated? I'm getting PS errors

### ISSUE THREAD

**Issue by Willtl** [yungshenglu/USTC-TK2016#13]
Unhandled Exception: System.TypeInitializationException: The type initializer for 'SplitCap.Program' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'PacketParser, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'PacketParser, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null'
   at SplitCap.Program..cctor()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

   --- End of inner exception stack trace ---
   at SplitCap.Program.Main(String[] args)

Unhandled Exception: System.TypeInitializationException: The type initializer for 'SplitCap.Program' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'PacketParser, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'PacketParser, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null'
   at SplitCap.Program..cctor()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

   --- End of inner exception stack trace ---
   at SplitCap.Program.Main(String[] args)
Error: No files matched '2_Session\AllLayers'
No files to process
Error: No files matched '2_Session\L7'
No files to process

**Comment by qq374107200** [comment]
WARNING: The runtime version supported by this application is unavailable.
Using default runtime: v4.0.30319

Unhandled Exception:
System.TypeLoadException: Could not load type of field 'SplitCap.Program:pcapWriters' (7) due to: Could not load file or assembly 'PacketParser, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type of field 'SplitCap.Program:pcapWriters' (7) due to: Could not load file or assembly 'PacketParser, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
WARNING: The runtime version supported by this application is unavailable.
Using default runtime: v4.0.30319

Unhandled Exception:
System.TypeLoadException: Could not load type of field 'SplitCap.Program:pcapWriters' (7) due to: Could not load file or assembly 'PacketParser, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type of field 'SplitCap.Program:pcapWriters' (7) due to: Could not load file or assembly 'PacketParser, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.

**Comment by cstsaitsaiyo** [comment]
Hello, download the SplitCap.exe file from [https://www.netresec.com/index.ashx?page=SplitCap](url), and replace the same file in 0_Tool\SplitCap_2-1 may work!

**Comment by Willtl** [comment]
I did my own scripts to filter the flow/sessions and create the figures.
